[phases.setup]
nixPkgs = [
  "python312",
  "glib",
  "pkg-config",
  "binutils",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "harfbuzz",
  "fontconfig",
  "freetype",
  "libffi"
]

[phases.build]
cmds = [
  "find /nix/store -name 'libgobject-2.0.so*' || true"
]
