[phases.setup]
nixPkgs = [
  "python312",
  "glib",
  "pkg-config",
  "binutils",
  "cairo",
  "pango",
  "harfbuzz",
  "gdk-pixbuf",
  "fontconfig",
  "freetype",
  "libffi"
]

[variables]
LD_LIBRARY_PATH="/root/.nix-profile/lib:/usr/lib"
PKG_CONFIG_PATH="/root/.nix-profile/lib/pkgconfig"
