# Generated by Django 6.0.6 on 2026-07-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuorder_id_alter_menusection_id_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuorder',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='menuorder',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='menuorder',
            name='rate',
        ),
    ]
